### PR TITLE
docs: Provide new website template

### PR DESCRIPTION
**Pull request by Mcalewaert**
Relates to https://github.com/arcus-azure/arcus.github.template

### CODE REVIEW

**Review by tomkerkhove — CHANGES_REQUESTED** [review]
Can we rename every page's title from `Scripts related to interacting with Azure API Management` to `Azure API Management` please?

**Comment by Mcalewaert** [comment]
@tomkerkhove Done

**Comment by mbraekman** [comment]
Small remark: can we indent the "Azure Blob Storage", "Azure File Share" and "Azure Table Storage" pages to become a sub-page of "Azure Storage"?

**Comment by Mcalewaert** [comment]
@mbraekman Was a bit harder than expected but storage files are now sitting inside an extra directory and I've added redirect rules for the old urls.

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
