### PR TITLE
fix: fix errors in documentation

### PR DESCRIPTION
**Pull request by fgheysels**
Edit code samples in SQL module documentation

### CODE REVIEW

**Review by stijnmoreels — APPROVED** [review]
👌 super. Thx!

**Comment by stijnmoreels** [comment]
I think this is already released, so you can update the documentation in the released docs too, if you want.

**Comment by fgheysels** [comment]
> I think this is already released, so you can update the documentation in the released docs too, if you want.

I'll see  how it can be done, and update this PR.

**Comment by fgheysels** [comment]
> > I think this is already released, so you can update the documentation in the released docs too, if you want.
> 
> I'll see how it can be done, and update this PR.

Should be done.

**Review by stijnmoreels — APPROVED** [review]
Great 👍

**Pull request merged**
