### PR TITLE
chore: frontend brand updates

### PR DESCRIPTION
**Pull request by stijnmoreels**
Use new frontend brand.

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Aha, now the deploy preview works.
Had to change the production branch in our Netlify documentation since we renamed our `master` branch to `main`.

**Review by pim-simons — APPROVED** [review]
Looks good to me 👍🏻

**Review by THMKAE — APPROVED** [review]
Is it possible to vertically center the arcus logo on the new diagram?

**Comment by stijnmoreels** [comment]
> Is it possible to vertically center the arcus logo on the new diagram?

I can try, but I also think that it is a bit an illusion as the logo has some empty space above the letters. So aligning it still feels off.

**Review by THMKAE — APPROVED** [review]

**Comment by stijnmoreels** [comment]
Ok, let's merge. First one that will get the new update! 🥇

**Pull request merged**
