### PR TITLE
Feature - create All metapackage

### LINKED ISSUE #66: Create metapackage: Arcus.Scripting
**Is your feature request related to a problem? Please describe.**
Create metapackage: Arcus.Scripting

**Describe the solution you'd like**
Create 1 package which imports all om the Arcus.Scripting.* modules.

### PR DESCRIPTION
**Pull request by stijnmoreels**
Creates a metapackage `Arcus.Scripting.All` which includes all the Arcus PS modules.

Closes #66

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Uses `Arcus.Scripting.Storage` from #125 but since only syntax will be checked, this is not a problem here.

**Comment by mbraekman** [comment]
Any reason this is called `Arcus.Scripting.All` and not just `Arcus.Scripting`?

**Comment by stijnmoreels** [comment]
> Any reason this is called `Arcus.Scripting.All` and not just `Arcus.Scripting`?

Ah, consistency with our other Arcus libraries and also something you see in other package groups. Like the `Microsoft.AspNetCore.All` package.
Seems like a good approach no? It explicitly shows that it contains everything on the topic.

**Comment by mbraekman** [comment]
> > Any reason this is called `Arcus.Scripting.All` and not just `Arcus.Scripting`?
> 
> Ah, consistency with our other Arcus libraries and also something you see in other package groups. Like the `Microsoft.AspNetCore.All` package.
> Seems like a good approach no? It explicitly shows that it contains everything on the topic.

Aha, yep if you tell it like that, seems like a good approach indeed 👍

**Review by mbraekman — APPROVED** [review]

**Pull request merged**
