### PR TITLE
feat: Add Remove-AzApiManagementUser script

### PR DESCRIPTION
**Pull request by pim-simons**
Added script to remove a user to an Azure API Management service.
Closes https://github.com/arcus-azure/arcus.scripting/issues/320

Note: cannot add integration tests as we don't have an Azure API Management service available in our resource group due to costs.

### CODE REVIEW

**Comment by pim-simons** [comment]
The name of the new script is `Remove-AzApiManagementUser`, as this follows our earlier scripts like `Create-AzApiManagementUser` for the user part and `Remove-AzApiManagementDefaults` for the remove part.

However this is also the name of the script in the `Az.ApiManagement` module, see https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuser?view=azps-8.2.0.

This caused some issues during unit testing, so some commands have the module specified, such as: 
https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-e1b36c2bbfb0483eb2ed4e8fd8e53e5497845e4459253c4cc182c14361734f11R1389
https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-e1b36c2bbfb0483eb2ed4e8fd8e53e5497845e4459253c4cc182c14361734f11R1406
https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-59aa3eb8ad259606b36e109cb8c6a4f4b532a886be3bff485dcbd01806da1739R31

During all my testing this wasn't an issue, but interested in if you think we should rename or not @stijnmoreels

**Comment by stijnmoreels** [comment]
> The name of the new script is `Remove-AzApiManagementUser`, as this follows our earlier scripts like `Create-AzApiManagementUser` for the user part and `Remove-AzApiManagementDefaults` for the remove part.
> 
> However this is also the name of the script in the `Az.ApiManagement` module, see https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuser?view=azps-8.2.0.
> 
> This caused some issues during unit testing, so some commands have the module specified, such as: https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-e1b36c2bbfb0483eb2ed4e8fd8e53e5497845e4459253c4cc182c14361734f11R1389 https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-e1b36c2bbfb0483eb2ed4e8fd8e53e5497845e4459253c4cc182c14361734f11R1406 https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-59aa3eb8ad259606b36e109cb8c6a4f4b532a886be3bff485dcbd01806da1739R31
> 
> During all my testing this wasn't an issue, but interested in if you think we should rename or not @stijnmoreels

Yeah, I think that we should rename this instead then. PowerShell let's you use it together with `-AlloClobber` but don't think this is a good approach, and I imagine many 'strange' behaviors if the users use the Azure variant.

Maybe we can add `...Account` to it? Like `Create-AzApiManagementUserAccount` and `Remove-AzApiManagementUserAccount`? It's find if the first one (create) is done in another PR to keep this one clean.

**Comment by pim-simons** [comment]
> > The name of the new script is `Remove-AzApiManagementUser`, as this follows our earlier scripts like `Create-AzApiManagementUser` for the user part and `Remove-AzApiManagementDefaults` for the remove part.
> > However this is also the name of the script in the `Az.ApiManagement` module, see [docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuser?view=azps-8.2.0](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuser?view=azps-8.2.0).
> > This caused some issues during unit testing, so some commands have the module specified, such as: [#321 (files)](https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-e1b36c2bbfb0483eb2ed4e8fd8e53e5497845e4459253c4cc182c14361734f11R1389) [#321 (files)](https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-e1b36c2bbfb0483eb2ed4e8fd8e53e5497845e4459253c4cc182c14361734f11R1406) [#321 (files)](https://github.com/arcus-azure/arcus.scripting/pull/321/files#diff-59aa3eb8ad259606b36e109cb8c6a4f4b532a886be3bff485dcbd01806da1739R31)
> > During all my testing this wasn't an issue, but interested in if you think we should rename or not @stijnmoreels
> 
> Yeah, I think that we should rename this instead then. PowerShell let's you use it together with `-AlloClobber` but don't think this is a good approach, and I imagine many 'strange' behaviors if the users use the Azure variant. We also used `Create-AzTableStorageAccountTable` to avoid calling it `New-AzStorageTable` in the Table Storage module.
> 
> Maybe we can add `...Account` to it? Like `Create-AzApiManagementUserAccount` and `Remove-AzApiManagementUserAccount`? (it's maybe even more clear then) It's fine if the first one (create) is done in another PR to keep this one clean.

Renamed the scripts to `Create-AzApiManagementUserAccount` and `Remove-AzApiManagementUserAccount` 👍🏻  Included the renaming of the create script in this PR as well, as I feel this is related to this PR (renaming only came up during development of the remove script). Thanks for your feedback!

**Review by stijnmoreels — APPROVED** [review]
Great! v0.7 is shaping to be an amazing release. Thx for this!

**Pull request merged**
