### PR TITLE
feat: Add APIM context validation

### PR DESCRIPTION
**Pull request by pim-simons**
Added context validation for Azure API Management. 

Closes https://github.com/arcus-azure/arcus.scripting/issues/220

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Ah, was I wrong in assuming that this comment: https://github.com/arcus-azure/arcus.scripting/issues/220#issuecomment-918892379 was outdated or something? I remember that when looking at the code, it only created a custom PS object, which of course is never `$null` , I figured that we needed some remote call to verify if the context represents a valid APIM.

**Comment by pim-simons** [comment]
> Ah, was I wrong in assuming that this comment: [#220 (comment)](https://github.com/arcus-azure/arcus.scripting/issues/220#issuecomment-918892379) was outdated? I remember that when looking at the code, it only created a custom PS object, which of course is never `$null` , I figured that we needed some remote call to verify if the context represents a valid APIM.

I mostly just took this from this comment here: https://github.com/arcus-azure/arcus.scripting/pull/206/files#diff-0479d3754dad91471518225257039759e3809046238bd16748e1e71adadc7eac: 
> This is indeed something that perhaps should be implemented on other scripts as well, just to have some additional line of validation to confirm whether the provided APIM-details are actually pointing towards a valid/existing instance.

So basically I added this part to the code where the APIM context is retrieved:
``` powershell
if ($apimContext -eq $null) {
    throw "Unable to find the Azure API Management Instance '$ServiceName' in resource group $ResourceGroupName"
}
```

But if I understand correctly we need some kind of remote call to validate? I wasn't onboard yet when the original discussion took place, so maybe I missed something 😉

**Comment by stijnmoreels** [comment]
> But if I understand correctly we need some kind of remote call to validate? I wasn't onboard yet when the original discussion took place, so maybe I missed something 😉

Yeah, seems like it. You can see it here: https://github.com/Azure/azure-powershell/blob/4668bff1cc4ed6510d9b0d4c6ec289ab27f04241/src/ApiManagement/ApiManagement.ServiceManagement/Commands/NewAzureApiManagementContext.cs

Mostly, the context is only created. Maybe there exists a `Contains API context` command somewhere to verify this, but to-be-analyzed. Maybe there is some kind of check hidden somewhere in the API Management commands.

**Comment by pim-simons** [comment]
Seems like using the approach used [here](https://github.com/arcus-azure/arcus.scripting/blob/master/src/Arcus.Scripting.ApiManagement/Scripts/Upload-AzApiManagementSystemCertificate.ps1#L14) might be a way to go.
This uses [Get-AzApiManagement](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/get-azapimanagement?view=azps-8.2.0) which gets the specific API Management instance so we can check if it actually exists.
@stijnmoreels what do you think?

**Comment by pim-simons** [comment]
> > Seems like using the approach used [here](https://github.com/arcus-azure/arcus.scripting/blob/master/src/Arcus.Scripting.ApiManagement/Scripts/Upload-AzApiManagementSystemCertificate.ps1?rgh-link-date=2022-08-17T09%3A00%3A55Z#L14) might be a way to go. This uses [Get-AzApiManagement](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/get-azapimanagement?view=azps-8.2.0) which gets the specific API Management instance so we can check if it actually exists. @stijnmoreels what do you think?
> 
> Aha, yeah, that could be a good alternative 👍

Appplied in [`1b62d75` (#317)](https://github.com/arcus-azure/arcus.scripting/pull/317/commits/1b62d758db6566bf0a948d42b022dbcaccb49a35)

**Comment by stijnmoreels** [comment]
> > > Seems like using the approach used [here](https://github.com/arcus-azure/arcus.scripting/blob/master/src/Arcus.Scripting.ApiManagement/Scripts/Upload-AzApiManagementSystemCertificate.ps1?rgh-link-date=2022-08-17T09%3A00%3A55Z#L14) might be a way to go. This uses [Get-AzApiManagement](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/get-azapimanagement?view=azps-8.2.0) which gets the specific API Management instance so we can check if it actually exists. @stijnmoreels what do you think?
> > 
> > 
> > Aha, yeah, that could be a good alternative 👍
> 
> Applied in [`1b62d75` (#317)](https://github.com/arcus-azure/arcus.scripting/pull/317/commits/1b62d758db6566bf0a948d42b022dbcaccb49a35)

Super! 👍 Great that you find this. Shame that there isn't a `.Context` property or something like that that we could use, but in any case, this alternative gives use enough security that the API Management service really exists.
Good job!

**Review by stijnmoreels — APPROVED** [review]

**Pull request merged**
